### ISSUE TITLE
[Discussion] Templating Engine 

### ISSUE THREAD

**Issue by dylantadros** [NandoSerrano85/CEN_Team7#4]
For the sake of brevity, I will just dictate this initial message to the thread as directed at the teammates who have less experience using the MEAN/MERN Stack...

Unlike most other HTTP(S) Servers/Engines - like NGINX, Apache, etc. - Express allows you to heavily and dynamically make edit to HTML and CSS via templating engines. These templating engines help keep the code short, and break it up into reusable elements. 

Two most useful engines from my experience are pug and EJS. _NOTE: handlebars is another templating engine but due to its similarity to pug and larger set of idiosyncrasies, pug usually takes the cake._

# pug
[Documentation](https://pugjs.org/api/getting-started.html)

- Python & Front-End Developer Friendly due to white-space syntax
- HTML/CSS based syntax
- Heavy Nesting/Mixins for large modular applications

# EJS
[Documentation](http://ejs.co/)

- Quicker development for more experience JS developers - or any OO or Functional developer (python, probably excluded)
- JS based syntax
- Slim Syntax
- Better Benchmarking

# 
 
Personally, I prefer EJS because of how clean the code looks; the ease with which you could use `includes`; the performance; and seamless integration with Node.js and Express.

**Comment by dylantadros** [comment]
_NOTE: I will be quickly dropping code starting from the Back-End to the Front-End; if I reach the front-end before we reach a decision I will just start with EJS for my sake...but would quickly translate it out to pug if we decide to make the migration...just lmk_

**Comment by NandoSerrano85** [comment]
i think going with ejs is the better choice in m opinion I've used it and like it

**Comment by dylantadros** [comment]
Let's just stick with that then.

I'll be updating the README.md either tonight or tomorrow with some information regarding the architecture of the project so that we could all stay on the same page and work cleanly and quickly....might also add a PRACTICES.md as a coding guideline...just because it seems the rest of the team might be less familiar with the MERN stack; and non-blocking asynchronousity does throw some people off when they first tackle it -- specially when it comes to recursion and event handling (AKA Express).

_Not to get off thread, but, @NandoSerrano85, would you mind collabing with me on the PRACTICES.md, a little, sometime early next week?_
